version: '4.36'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: practica3
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  tomcat:
    build: .
    container_name: tomcat
    ports:
      - "8085:8080"
    depends_on:
      - mariadb
    environment:
      - JDBC_URL=jdbc:mariadb://mariadb:3306/practica3
      - JDBC_USER=admin
      - JDBC_PASSWORD=123456

volumes:
  mariadb_data:
